Spring:
    profiles:
       active:
       -dev
---
spring:
   profiles: dev        # 开发环境
   application:
       name: springcloudconfig-dev     
---
spring:
   profiles: uat        # 测试环境
   application:
       name: springcloudconfig-uat     
# 一定要保存为utf-8的格式
 